---
title: "About the Author"
---


My name is Armaan Sodhi I am a second year MPH student at Columbia University. I am currently studying Epidemiology and Applied Biostastics and Public Health Data Science. I am a graduate researcher at Columbia University and also a policy researcher at Sachs Policy Group. I will graduate from Columbia in May of 2023.

Before this I had attended the University of California, Riverside where I graduated Cum Laude with a Bachelor of Arts in Public Policy. 

## PROFESSIONAL EXPERIENCE

* **Intern at Sachs Policy Group**                                           *9/22-Present* 

   + Responsible to support senior leadership in developing strategy by leveraging healthcare data analytics to create reports and presentations for C level executives in the healthcare industry 

* **Columbia University Mailman School of Public Health, Graduate Researcher** 
*4/22-Present*

   + Using large scale complex clinical data to study COVID-19s effects on minority healthcare workers in New York State

   + The study will culminate into a published paper in a research journal where I will be the first author

   + Interpreting, analyzing, and modeling quantitative data from COVID-19 Healthcare Personnel Study 

   + Presenting Poster at the 2022 Annual American Public Health Association Expo

   + Performing Literature Review, including market research involving supply and demand of PPE distribution  

### University of California, Riverside

* **Research Assistant for “Anti-Racism Committee” with Healthy Campus**     *7/20 - 10/20*

   + Recruited by lead professor for project that consisted of researching racism at UC Riverside and implementing equity, inclusion, and diversity programs to address racism and effects on student/faculty health

   + Achievements included facilitator of large focus groups (80+ people) and qualitative data analyst  

   + Research findings caused the establishment of the Anti-Racism Subcommittee at Healthy Campus 

* **Project Leader at Voicing Collegiate Recovery**	      *3/20 – 3/21* 

   + Project consisted of researching causes and provided solutions to college aged substance use and recovery

   + Project Managed a diverse team for Engagement Committee as part of Voicing Collegiate Recovery Symposium

   + I went from a student researcher to a member of the Steering Committee in less than 6 months

   + Facilitated the Open Discussion Meeting (30+ People), moderated focus groups, and resolved conflicts 

   + Coauthored technical research paper on topic of recommendations for research in collegiate recovery which was shown during symposium

* **Research Assistant at the Blum Initiative**	            6/19-6/21;

   + Recruited by head of the Blum Initiative to join the Public Policy study on poverty and health care (including Medicaid)

   + In 1-on-1 setting, administered surveys to California Senators and Assemblymen about attitudes toward poverty 

   + Further achievements included collaborating with program advisors to improve survey quality

* **Fitness + Health + Fashion Review, Assistant**	9/16 – 08/21;

   + Web hosting services and design lead at family owned and operated online business at http://www.reviewfithealth.com

   + Technical accomplishments included optimizing SEO and Google AdSense leading to a 300% growth in advertising revenue 

## AWARDS
	Dean's List	2017-2018, 2019-2020, 2020-2021
	Chancellors List	2017-2018, 2019-2020, 2020-2021
	Selected to the UCR Chapter of the National Society of Leadership and Success	2017-2021
	Graduated Cum Laude from the University of California, Riverside

## PUBLICATIONS / RESEARCH

* A. SODHI, The Highlander Newspaper Article by Armaan Sodhi, Staff Writer; ASUCR and Career Center collaborate on “Present Yourself In The Best Light” event
* Vasquez E., Cravahlho D., Ryan-Shirey F.,Currie M., Westergaard R., Brara B., Sodhi A.… Cheney A. (2020). Voices of Collegiate Recovery Facilitator Report. Riverside, CA.
* Anti-Racism Project - Contributed as part of the student team to a technical paper identifying institutional racism and potential solutions at UCR as part of student team

